#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Error - Number missing form command line argument"
	echo "Syntax : $0 number "
	echo "Example : $0 2"
	exit 1
fi

n=$1
i=1

while [ $i -le 12 ]
do
	echo "$n * $i = `expr $n \* $i`"
	i=`expr $i + 1`
done


